"""add users and buses

Revision ID: f3dabd63a0fb
Revises: 69c7b643f399
Create Date: 2026-02-17 13:07:40.097577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3dabd63a0fb'
down_revision: Union[str, Sequence[str], None] = '69c7b643f399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bus_number', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_bus_number'), 'buses', ['bus_number'], unique=False)
    op.create_index(op.f('ix_buses_company_id'), 'buses', ['company_id'], unique=False)
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=False)
    op.create_index(op.f('ix_buses_route'), 'buses', ['route'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_companies_bin'), 'companies', ['bin'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.alter_column('complaints', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('complaints', 'bus_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_complaints_bus_id'), 'complaints', ['bus_id'], unique=False)
    op.create_index(op.f('ix_complaints_company_id'), 'complaints', ['company_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.drop_constraint('complaints_company_id_fkey', 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'complaints', 'buses', ['bus_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key('complaints_company_id_fkey', 'complaints', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_company_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_bus_id'), table_name='complaints')
    op.alter_column('complaints', 'bus_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('complaints', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_bin'), table_name='companies')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_buses_route'), table_name='buses')
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_company_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_bus_number'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
